DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products
(
    id BIGINT PRIMARY KEY,
    building_id VARCHAR(255) NOT NULL,
    related_unit VARCHAR(255) NOT NULL,
    category_type VARCHAR(255) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    quantity_type VARCHAR(255) NOT NULL,
    product_tech_code VARCHAR(255) NOT NULL,
    room_name_of_installation VARCHAR(255) NOT NULL,
    delivery_type VARCHAR(255),
    room_plan_code VARCHAR(255),
    time_of_order TIMESTAMP,
    delivery_note_id VARCHAR(255),
    time_of_arrived_at_site TIMESTAMP,
    place_of_storage VARCHAR(255),
    time_of_installed TIMESTAMP,
    time_of_record TIMESTAMP,
    last_time_of_modified TIMESTAMP
);

ALTER TABLE products
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO products (building_id, related_unit, category_type, product_name, quantity, quantity_type, product_tech_code, room_name_of_installation, delivery_type, room_plan_code, time_of_order, delivery_note_id, time_of_arrived_at_site, place_of_storage, time_of_installed, time_of_record, last_time_of_modified)
VALUES
    ('VII', '1', 'parketta', 'tölgy juhar', 2.0, 'nm', '053900699', 'nappali', 'generalDelivery', 'N-05',
     '2023-07-03 12:00:00', '1568', '2023-07-03 14:30:00', 'P1 raktar', '2023-07-04 10:00:00', '2023-07-04 09:00:00', '2023-07-04 09:00:00'),
    ('XI', '2', 'világítás', 'led', 10.0, 'db', '021483965', 'hálószoba', NULL, 'N-07', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('IX', '1', 'szőnyeg', 'minta', 3.5, 'm2', '035792108', 'étkező', 'expressDelivery', 'N-02', '2023-07-05 09:30:00', '2468', '2023-07-05 12:15:00', 'P2 raktár', '2023-07-06 15:30:00', '2023-07-06 13:45:00', '2023-07-06 13:45:00'),
    ('V', '1', 'fürdőszoba', 'mosdó', 1.0, 'db', '084536273', 'fürdőszoba', 'generalDelivery', 'N-03', '2023-07-07 11:45:00', '3579', '2023-07-07 14:20:00', 'P1 raktár', '2023-07-08 09:15:00', '2023-07-08 08:30:00', '2023-07-08 08:30:00'),
    ('III', '2', 'konyha', 'sütő', 1.0, 'db', '098765432', 'konyha', NULL, 'N-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ( 'X', '1', 'ágy', 'dupla', 1.0, 'db', '024680246', 'hálószoba', 'expressDelivery', 'N-05', '2023-07-09 10:30:00', '1234', '2023-07-09 13:15:00', 'P2 raktár', '2023-07-10 11:30:00', '2023-07-10 10:00:00', '2023-07-10 10:00:00'),
    ('II', '1', 'asztal', 'fa', 1.0, 'db', '065432109', 'nappali', 'generalDelivery', 'N-06', '2023-07-11 14:00:00', '7890', '2023-07-11 16:45:00', 'P1 raktár', '2023-07-12 13:30:00', '2023-07-12 12:15:00', '2023-07-12 12:15:00'),
    ( 'VI', '3', 'könyvszekrény', 'fekete', 2.0, 'db', '037291048', 'nappali', NULL, 'N-08', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('VIII', '1', 'szék', 'műanyag', 4.0, 'db', '057609873', 'étkező', 'expressDelivery', 'N-09', '2023-07-13 09:15:00', '1357', '2023-07-13 11:50:00', 'P2 raktár', '2023-07-14 10:30:00', '2023-07-14 09:45:00', '2023-07-14 09:45:00'),
    ( 'IV', '2', 'kanapé', 'bőr', 1.0, 'db', '098765432', 'nappali', 'generalDelivery', 'N-10', '2023-07-15
    12:30:00', '2468', '2023-07-15 15:05:00', 'P1 raktár', '2023-07-16 14:00:00', '2023-07-16 12:45:00', '2023-07-16 12:45:00');
